name: pages-build-deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: actions/checkout@v4

    - name: Deploy
      # 如果使用 GitHub Pages 部署动作，可以这样配置
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: '.' # 确保这里指向你的构建输出目录
      # 输出部署链接
      - name: Output Deployment URL
        run: echo "访问
